const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate PDF Report - Summary Version
 */
function generateSummaryPDF(analysisData, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(outputPath);
      
      doc.pipe(stream);
      
      // Header with logo (text-based for now)
      doc.fontSize(24).fillColor('#0ea5e9').text('AEO Suite Analysis Report', { align: 'center' });
      doc.fontSize(10).fillColor('#64748b').text('by Thatworkx', { align: 'center' });
      doc.moveDown(2);
      
      // URL and Date
      doc.fontSize(12).fillColor('#1e293b').text(`URL: ${analysisData.url}`);
      doc.fontSize(10).fillColor('#64748b').text(`Date: ${new Date(analysisData.createdAt).toLocaleDateString()}`);
      doc.moveDown(1);
      
      // Overall Score Box
      doc.rect(50, doc.y, 495, 80).fillAndStroke('#0ea5e9', '#0ea5e9');
      doc.fontSize(14).fillColor('#ffffff').text('Overall AEO Score', 60, doc.y + 15);
      doc.fontSize(48).fillColor('#ffffff').text(`${analysisData.overallScore}`, 60, doc.y + 10);
      doc.fontSize(16).fillColor('#ffffff').text(`Grade: ${getGradeLetter(analysisData.overallScore)}`, 200, doc.y - 35);
      doc.moveDown(6);
      
      // Individual Analyzer Scores
      doc.fontSize(16).fillColor('#1e293b').text('Analyzer Scores', { underline: true });
      doc.moveDown(0.5);
      
      const analyzers = [
        { name: 'Technical Foundation', key: 'technicalFoundation', weight: '25%' },
        { name: 'Content Structure', key: 'contentStructure', weight: '25%' },
        { name: 'Page-Level E-E-A-T', key: 'pageLevelEEAT', weight: '20%' },
        { name: 'Query Match', key: 'queryMatch', weight: '15%' },
        { name: 'AI Visibility', key: 'aiVisibility', weight: '15%' }
      ];
      
      analyzers.forEach(analyzer => {
        const data = analysisData[analyzer.key];
        doc.fontSize(12).fillColor('#1e293b')
          .text(`${analyzer.name} (${analyzer.weight}):`, 60, doc.y)
          .text(`${data.score}/100 (${data.grade})`, 400, doc.y - 12, { align: 'right' });
        doc.moveDown(0.5);
      });
      
      doc.moveDown(1);
      
      // Top 5 Recommendations
      doc.fontSize(16).fillColor('#1e293b').text('Top Priority Recommendations', { underline: true });
      doc.moveDown(0.5);
      
      const allRecommendations = [];
      analyzers.forEach(analyzer => {
        const data = analysisData[analyzer.key];
        if (data.recommendations && data.recommendations.length > 0) {
          data.recommendations.forEach(rec => {
            allRecommendations.push({
              text: typeof rec === 'string' ? rec : rec.text,
              priority: rec.priority || 'medium',
              analyzer: analyzer.name
            });
          });
        }
      });
      
      const priorityOrder = { critical: 1, high: 2, medium: 3, low: 4 };
      allRecommendations.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);
      
      allRecommendations.slice(0, 5).forEach((rec, index) => {
        doc.fontSize(10).fillColor('#0ea5e9').text(`${index + 1}. `, 60, doc.y, { continued: true });
        doc.fillColor('#1e293b').text(rec.text);
        doc.fontSize(8).fillColor('#64748b').text(`   [${rec.analyzer} - ${rec.priority.toUpperCase()}]`);
        doc.moveDown(0.5);
      });
      
      doc.moveDown(1);
      
      // Footer
      doc.fontSize(8).fillColor('#64748b')
        .text('Generated by AEO Suite - Answer Engine Optimization by Thatworkx', 50, doc.page.height - 50, { align: 'center' });
      doc.text('https://aeo.thatworkx.com', { align: 'center' });
      
      doc.end();
      
      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
      
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate PDF Report - Detailed Version
 */
function generateDetailedPDF(analysisData, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(outputPath);
      
      doc.pipe(stream);
      
      // Header with logo
      doc.fontSize(24).fillColor('#0ea5e9').text('AEO Suite - Detailed Analysis Report', { align: 'center' });
      doc.fontSize(10).fillColor('#64748b').text('by Thatworkx', { align: 'center' });
      doc.moveDown(2);
      
      // URL and Date
      doc.fontSize(12).fillColor('#1e293b').text(`URL: ${analysisData.url}`);
      doc.fontSize(10).fillColor('#64748b').text(`Date: ${new Date(analysisData.createdAt).toLocaleDateString()}`);
      if (analysisData.targetKeywords && analysisData.targetKeywords.length > 0) {
        doc.text(`Keywords: ${analysisData.targetKeywords.join(', ')}`);
      }
      doc.moveDown(1);
      
      // Overall Score
      doc.rect(50, doc.y, 495, 80).fillAndStroke('#0ea5e9', '#0ea5e9');
      doc.fontSize(14).fillColor('#ffffff').text('Overall AEO Score', 60, doc.y + 15);
      doc.fontSize(48).fillColor('#ffffff').text(`${analysisData.overallScore}`, 60, doc.y + 10);
      doc.fontSize(16).fillColor('#ffffff').text(`Grade: ${getGradeLetter(analysisData.overallScore)}`, 200, doc.y - 35);
      doc.moveDown(6);
      
      // Detailed Analyzer Sections
      const analyzers = [
        { name: 'Technical Foundation', key: 'technicalFoundation', weight: '25%' },
        { name: 'Content Structure', key: 'contentStructure', weight: '25%' },
        { name: 'Page-Level E-E-A-T', key: 'pageLevelEEAT', weight: '20%' },
        { name: 'Query Match', key: 'queryMatch', weight: '15%' },
        { name: 'AI Visibility', key: 'aiVisibility', weight: '15%' }
      ];
      
      analyzers.forEach((analyzer, index) => {
        // Add new page for each analyzer except first
        if (index > 0) doc.addPage();
        
        const data = analysisData[analyzer.key];
        
        // Analyzer Header
        doc.fontSize(18).fillColor('#0ea5e9').text(`${analyzer.name}`, { underline: true });
        doc.fontSize(12).fillColor('#64748b').text(`Weight: ${analyzer.weight}`);
        doc.moveDown(0.5);
        
        // Score Box
        doc.fontSize(14).fillColor('#1e293b').text(`Score: ${data.score}/100 (Grade ${data.grade})`);
        doc.moveDown(1);
        
        // Recommendations
        doc.fontSize(14).fillColor('#1e293b').text('Recommendations:', { underline: true });
        doc.moveDown(0.5);
        
        if (data.recommendations && data.recommendations.length > 0) {
          data.recommendations.slice(0, 10).forEach((rec, i) => {
            const recText = typeof rec === 'string' ? rec : rec.text;
            const priority = rec.priority || 'medium';
            const priorityColor = priority === 'critical' ? '#dc2626' : priority === 'high' ? '#ea580c' : '#64748b';
            
            doc.fontSize(10).fillColor(priorityColor).text(`${i + 1}. [${priority.toUpperCase()}]`, 60, doc.y, { continued: true });
            doc.fillColor('#1e293b').text(` ${recText}`);
            
            if (rec.why) {
              doc.fontSize(9).fillColor('#64748b').text(`   Why: ${rec.why}`);
            }
            if (rec.howToFix) {
              doc.fontSize(9).fillColor('#64748b').text(`   How to fix: ${rec.howToFix}`);
            }
            
            doc.moveDown(0.5);
          });
        } else {
          doc.fontSize(10).fillColor('#64748b').text('No recommendations available.');
        }
      });
      
      // Footer on last page
      doc.fontSize(8).fillColor('#64748b')
        .text('Generated by AEO Suite - Answer Engine Optimization by Thatworkx', 50, doc.page.height - 50, { align: 'center' });
      doc.text('https://aeo.thatworkx.com', { align: 'center' });
      
      doc.end();
      
      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
      
    } catch (error) {
      reject(error);
    }
  });
}

function getGradeLetter(score) {
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  return 'F';
}

module.exports = {
  generateSummaryPDF,
  generateDetailedPDF
};